### ISSUE TITLE
Research objects vs. research outputs.

### ISSUE THREAD

**Issue by kristiholmes** [data2health/research-outputs-ontology#1]
Would it be possible to rename repo as research objects ontology? This will allow us to be more inclusive of objects that might not necessarily be outputs. Thoughts? Thanks.

**Comment by mellybelly** [comment]
Maybe... not opposed, but would this be confusing with the workflows represented by researchobject.org?

**Comment by pnrobinson** [comment]
Please forgive this slightly off-topic remark, but the name Research Objects Ontology would open the door to an amazing ontology mascot: https://en.wikipedia.org/wiki/Roo :-0
and I agree it is not all "outputs".

**Comment by nicolevasilevsky** [comment]
The decision was made in Chicago to rename the ontology to Research Artefacts Ontology, so I think we can close this ticket. Reopen if needed.
