### ISSUE TITLE
should terms be plural?

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/research-outputs-ontology#4]
some of the terms I added are plural (because that is how they were written in the [spreadsheet](https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=1619162717), but I just want to confirm that I should make them singular

**Comment by marijane** [comment]
Closing because we are not going to pursue creation of the ROO/RAO.
