### ISSUE TITLE
decide between created_by vs dc:creator

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/research-outputs-ontology#5]
HPO uses created_by (as of just recently), so the new term I just added to ROO (ROO_0000036) has the annotation created_by, whereas the other classes use dc:creator.

Is it okay if we use created_by instead of dc:creator?

Is there any easy way to update annotations on the other classes I created? If not, I can do it manually.

**Comment by marijane** [comment]
Closing because we are not going to pursue creation of the ROO/RAO.
