### ISSUE TITLE
need dbxref annotation property

### ISSUE THREAD

**Issue by nicolevasilevsky** [data2health/research-outputs-ontology#6]
all the imports brought in a lot of new annotation properties, but it appears we still do not have the dbxref annotation property.

Should we add it to the IAO imports? 

Once we add it, we should add xrefs from the [spreadsheet](https://docs.google.com/spreadsheets/d/1Mw8gK2NUGM8po7GGRtJTShRM2QNFoR19VJrjQuVCDW8/edit#gid=1619162717)

**Comment by marijane** [comment]
Closing because we are not going to pursue creation of the ROO/RAO.
